### ISSUE TITLE
Update learning in each project based on README files of individual projects

### ISSUE THREAD

**Issue by saurabhnative** [codeclassifiers/create_react_projects#1]
The repository contains links to 15 open-sourced react projects. 
Each project has it's own README containing a `Learnings` section.
We need to update the README in this repo with learnings listed in each individual project.
Sample learnings are added in first 2-3 projects as per README in each individual project.
This needs to be done for all the 15 projects listed.

**Comment by bineetNaidu** [comment]
I would like to contribute onto this project. Feel free to assign me this task.

**Comment by saurabhnative** [comment]
@bineetNaidu Issue is assigned to you. You can make the required changes.

**Comment by SubahanM** [comment]
i would like to contribute onto this project

**Comment by aaronjtom** [comment]
I would like to contribute to this issue

**Comment by saurabhnative** [comment]
@subahan8055 and @AaronF3PS  Issue is assigned to you. You both can make the required changes.
